version: '3'

services:
  synapse:
    image: matrixdotorg/synapse:v1.90.0
    volumes:
      - ./synapse-data:/data
      - ./nginx/auth.example.com.crt:/etc/ssl/certs/ca-certificates.crt
    depends_on:
      - auth
    environment: 
      - UID=${MYUID}
      - VIRTUAL_PORT=8008
      - VIRTUAL_HOST=matrix.example.com
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - oidc

  auth:
    image: yadd/lemonldap-ng-portal
    volumes:
      - ./lemonldap/lmConf-1.json:/var/lib/lemonldap-ng/conf/lmConf-1.json
      - ./lemonldap/ssl.conf:/etc/nginx/sites-enabled/0000default.conf
      - ./nginx/auth.example.com.crt:/etc/nginx/ssl/auth.example.com.crt
      - ./nginx/auth.example.com.key:/etc/nginx/ssl/auth.example.com.key
    environment:
      - PORTAL=https://auth.example.com
      - VIRTUAL_HOST=auth.example.com
    networks:
      oidc:
        aliases:
          - auth.example.com

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx:/etc/nginx/certs

networks:
  oidc:
    name: oidc